### ISSUE TITLE
User editing

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#100]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

When I go to edit a user to change some aspects such as name, username, email....when I save it tells me that the repetition of the password is missing but clearly I don't want to change it

![Image](https://github.com/user-attachments/assets/213dd753-e3f5-4bd1-a68b-11d1b3aca056)

### Steps to reproduce

1. Go in the user list
2. Edit a user
3. Change same values
4. Save

### Environment

3.8.dev-20241016143931

### Link to your project

https://dev.g3wsuite.it/it/users/update/44/

**Comment by wlorenzetti** [comment]
@leolami you have to clear the Password field e send the form.

**Comment by leolami** [comment]
I understand, but it's not exactly intuitive for an external user....

**Comment by wlorenzetti** [comment]
Because your user and password are saved in the browser.. and is not possible make it in other way :)

**Comment by Raruto** [comment]
@wlorenzetti

- https://www.w3schools.com/howto/howto_html_autocomplete_off.asp
- https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Turning_off_form_autocompletion

**Comment by wlorenzetti** [comment]
> @wlorenzetti
> 
>     * https://www.w3schools.com/howto/howto_html_autocomplete_off.asp
> 
>     * https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Turning_off_form_autocompletion

@Raruto thanks!

**Comment by wlorenzetti** [comment]
@Raruto I just make a test but it seem not works:
![Screenshot_20241021_093748](https://github.com/user-attachments/assets/885a4162-57a3-4f18-81f9-662317ed726c)

**Comment by Raruto** [comment]
I think it's just your old browser cache, mdndocs states:

> If a browser keeps on making suggestions even after setting autocomplete to off, then you have to change the name attribute of the <input> element.
