### ISSUE TITLE
Relations editing: error

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#105]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

When I click on these icons the client freezes

![Image](https://github.com/user-attachments/assets/e107ff6c-052e-46e8-8046-f97713e3fd79)

### Steps to reproduce

Try to edit on IRPI project

### Environment

 3.8.dev-20241018150811

### Link to your project

http://db.irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/

**Comment by volterra79** [comment]
@leolami i tried but it works.
