### ISSUE TITLE
Creation of new geometry on related layer not saved correctly

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#106]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

The survey seems to be correctly inserted and saved but if I refresh the client the survey disappears...

It seems like a specific case related to this project/layer

### Steps to reproduce

1. Edit the **Intorni morfologici** layer
2. Go to session **C6**
3. Add an **Alluvione associata**
4. Create it, save and exit editing
5. The geometry can be seen
6. Refresh the client, the geometry is disappear

![Image](https://github.com/user-attachments/assets/820b13df-677e-48af-9cea-5b1262af2d56)

All works wll thi the layer **Frane associate**

### Environment

3.8.dev-20241018150811

### Link to your project

http://db.irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/

**Comment by volterra79** [comment]
@leolami i tried and it works
