### ISSUE TITLE
Camaiore: richiesta cambio ip

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#114]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

Bisognerebbe provvedere al cambio IP chiesto da Galluzzo nella telefonata che hai avuuto con lui

Nono stante tutto ci pagano 2K annue, per quasi nulla...

### Suggested solution

Cambio Ip, se non ti ricordi chiama Galluzzo

**Comment by wlorenzetti** [comment]
Gia fatto e funzionante scrivo a galluzzo
