### ISSUE TITLE
CLIENT: Features filter error

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#13]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

Any features visualized after filtering

### Steps to reproduce

See the attacched video

https://109.71.235.151/it/map/verde-pubblico/

### Environment

- g3w-admin: __v3.7.4__
- g3w-client: __3.9.3__
- browser: __Chrome 120.0.0.0__
- operating system: __Linux 64-bit__

**Comment by wlorenzetti** [comment]
@leolami video is missing

**Comment by leolami** [comment]
I have an error on upload file

I send it to you by mail

**Comment by wlorenzetti** [comment]
Closes by https://github.com/g3w-suite/g3w-admin/pull/753
