### ISSUE TITLE
G3W-Suite: new customer

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#15]
Prepare a new installation on one of our servers, even if shared with others, with URL sit.andreotti.g3wsuite.it or if possible sit.andreotti.g3wsuite.ch

Basic installation without modules

Immediately expand the number and size of files that can be uploaded to FileManager and set the QGIS API instead of WMS

**Comment by wlorenzetti** [comment]
@leolami  `sit.andreotti.g3wsuite.ch` is possible if we buy new domain `g3wsuite.ch`

**Comment by leolami** [comment]
g3wsuite.it is right

**Comment by wlorenzetti** [comment]
@leolami  nella email ho visto che hai messo 500G di spazio ma nell'hostin condiviso questo non lo abbiamo a meno che non monti un volume aggiuntivo

**Comment by wlorenzetti** [comment]
Scusa niente 500MB ok

**Comment by wlorenzetti** [comment]
@leolami https://sit.andreotti.g3wsuite.it pronto.
