### ISSUE TITLE
Error in the contents reported in the printout

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#17]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

The layers shown in print do not reflect those displayed on the map

I would like to point out that the print layout is not associated with any view/theme and therefore the layers shown must only be those visible on the map at the time of printing

### Steps to reproduce

1. Go to https://v37.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/
2. Switch off the ROADS layer in the TOC
3. Create a Print based on A4 Orizzontal layot
4. In the PDF ROADS will appear

### Environment

- g3w-admin: __3.7.x-20240223094316__
- g3w-client: __3.9.3__
- browser: __Chrome 122.0.0.0__
- operating system: __Windows 10 64-bit__

### Link to your project

https://v37.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/

**Comment by wlorenzetti** [comment]
@leolami openi

ng the project inside QGIS desktop (3.34) and looking inside the A4 horizontal layout, I see that in the main map image property is checked this:


![Image](https://github.com/g3w-suite/backlog/assets/196809/9f0f3269-ac8a-462c-8cdb-dfd7814f1991)

un-checking the options and reloading the project, after on G3W-SUITE it seems work fine.

**Comment by leolami** [comment]
The problem. apparently resolved on the test webgis, it remains on a Quarrata webgis in a very random way....

https://sit.comunequarrata.duckdns.org/it/map/piano-operativo-2020/qdjango/1/

Position yourself at 1:1,000 scale and print based on the "A4 horizontal" layout, always 1:1,000

The "civic, road and cadastral parcels" layers probably do not appear correctly in the PDF

But if you try to create prints, one after the other (see video), the result is always different....

In the QGIS project (3.28) the Lock layer option is disabled.

https://github.com/g3w-suite/backlog/assets/4012899/934f3d7c-44aa-4c85-b052-c35afd1dd97c
