### ISSUE TITLE
Correggere bug su gitlab

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#35]
Promemoria per correzzione bug segnalati da loro in particolare questi:

https://gitlab.gis3w.it/gis3w/blueoak/issues/9

https://gitlab.gis3w.it/gis3w/blueoak/issues/8

Oltre al mio

https://gitlab.gis3w.it/gis3w/blueoak/issues/10

**Comment by Raruto** [comment]
@leolami can I close this task?

**Comment by leolami** [comment]
Yes, thank you
