### ISSUE TITLE
New CNR-IRPI server

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#41]
### Checklist

- [ ] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

Come abbiamo detto occorrerebbe una VM dedicata a CNR-IRPI con i seguenti applicativi:

G3W-SUITE DEV
POSTGIS per i dati

In futuro andrà installato anche MERGIN con sistema sincornizzazione dei dati PostGis

### Suggested solution

Vm dedicata

**Comment by wlorenzetti** [comment]
Come si chiama il progetto/bando?
