### ISSUE TITLE
Time series on v3.7

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#46]
### Checklist

- [ ] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

The Time Series does'nt work anymore on v37

https://v37.g3wsuite.it/it/map/timeseries/

It works on dev

https://dev.g3wsuite.it/en/map/timeseries/

### Steps to reproduce

Go on https://v37.g3wsuite.it/it/map/timeseries/

### Environment

- g3w-admin: __version__
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

**Comment by volterra79** [comment]
@leolami https://github.com/g3w-suite/g3w-admin/pull/814 solve the issue

**Comment by leolami** [comment]
@wlorenzetti can you update v3.7 on line?

**Comment by wlorenzetti** [comment]
@leolami I just update v37, please just checkt the issu e and replay me so I can release new v3.7.8. Thanks
