### ISSUE TITLE
Installazione modulo Catasto

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#49]
### Checklist

- [ ] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

Occorre installare il modulo catasto nell'attuale installazione 3.6 di Città Metropolitana Roma

Poi seguo io il resto

### Suggested solution

Installazione modulo

**Comment by wlorenzetti** [comment]
@leolami fatto.
