### ISSUE TITLE
User themes: delete problem

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#59]
### Checklist

- [ ] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

Deleting user themes does not update automatically

The deletion procedure is successful but if I refresh the map the deleted user theme reappears

### Steps to reproduce

1. Create a user theme
2. Delete the user theme
3. refresh the mapp
4. You can see the deleted user theme in the list

### Environment

 g3w-admin: __3.8.download_pdf_attributes-20240514124301__
- g3w-client: __3.10.0-alpha.2__
    - editing: __3.8.0-alpha.1__
    - qplotly: __undefined__
    - qtimeseries: __undefined__
- browser: __Chrome 124.0.0.0__
- operating system: __Windows 10 64-bit__

**Comment by volterra79** [comment]
@leolami i can't reproduce it

**Comment by wlorenzetti** [comment]
@leolami make attention on branch _g3w-admin: 3.8.download_pdf_attributes-20240514124301_
