### ISSUE TITLE
Attivazione zoomhistory su Lavino Samoggia

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#62]
Puoi farlo?

COme mai non è di default come gli altri?

Senza fretta

**Comment by wlorenzetti** [comment]
Ma abbiamo gia aggiornato alla 3.7?

**Comment by leolami** [comment]
Ops...no...

Allora bisognerebbe farlo che ci sono le ricerche che non funzionano

**Comment by wlorenzetti** [comment]
Allora scrivigli che lo faccio mercoledì mattina che non ci lavorino, o altrimenti giovedì mattina come preferiscono loro
