### ISSUE TITLE
New file type to upload

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#76]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

Non è possibile caricare come allegato file ZIP e GPKG

DOvrebbero essere aggiunti ai file gestiti

### Steps to reproduce

Prova a caricare uno di questi file come allegato

### Environment

v 3.8.1

**Comment by wlorenzetti** [comment]
Prova ora dovrebbe funzionare
