### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#80]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

Sul client di questa installazione andrebbe tolto il menù Credits in alto a destra

https://webgis.apda.ecomuseolisaganis.it

Grazie

### Suggested solution

Custom CSS

**Comment by volterra79** [comment]
@wlorenzetti 

```
li.dropdown.user.user-menu:has(a[data-target="#credits"]) {
    display: none;
}
```

**Comment by wlorenzetti** [comment]
@leolami fatto
