### ISSUE TITLE
Parco Apuane: nuova installazione

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#84]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

Creare una nuova installazione su un server a tua scelta (anche senza certificazioni) per il Parco delle Apuane

### Suggested solution

Installazione base

Nessun modulo aggiuntivo

Sbloco numero e dimensioni file su FileManager

Come URL vedi te. ad esempio https://www.g3wsuite.parcapuane.it

**Comment by leolami** [comment]
@wlorenzetti mandami lo zip dei dati geografici presenti sull'attuale server

**Comment by wlorenzetti** [comment]
Trovi utente e password e dati qui:
https://drive.google.com/drive/u/0/folders/1daiXRSlnbGJHjzQVZdwGBmIF0oHhThup

**Comment by leolami** [comment]
Dovresti sbloccare il limite sul File Manager

Numero file: 100
Dimensione 100 MB

Grazie
