### ISSUE TITLE
Download layer: server error

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#85]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

https://gis.ilbarone.net/it/map/pieve_a_nievole_catasto_arboreo/

### Steps to reproduce

Prova a scaricare layer ALBERI in uno dei formati previsti

### Environment

- g3w-admin: __version__
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

**Comment by wlorenzetti** [comment]
@leolami dati malformati:
![Image](https://github.com/user-attachments/assets/58442eb6-bfc2-4699-b09c-b9909a475e0a)

Ma com'è possibile una cosa del genere se sul campo c'è un vincolo?
