### ISSUE TITLE
SEARCH CREATION: error on joined fields

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#86]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

Quando si prova a creare una rcierca basata su un campo in join, il tasto OK per creare la ricerca non determina nessuna azione, ovvero al chiusura del form e il salvataggio della ricerca

https://gis.ilbarone.net/it/admin/qdjango/comune-pieve-nievole/projects/comune-di-pieve-a-nievole-catasto-arboreo/layers/

### Steps to reproduce

Crea una ricerca sul layer **ALBERi** basata sul campo **Q_MAX_TOR** che è un campo in join

La tabella in join si chiama **ToR**

### Environment

- g3w-admin: __version__
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

**Comment by wlorenzetti** [comment]
E' bastato risalvare il progetto, molto probabilmente era stato salavato prima della possibilità di avere layer in relazione nelle ricerche.
@leolami
