### ISSUE TITLE
IP FISSO

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#89]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

Creare IP FISSO per test timeout server

### Suggested solution

Non so se devi fare un'installazione ad hoc o possiamo usare un nostro test con stessa versione loro

**Comment by wlorenzetti** [comment]
IP fisso ce lo abbiamo quando creiamo la macchina.

**Comment by leolami** [comment]
Ok, allora facciamo la macchina poi organizzo io con Volpe

**Comment by wlorenzetti** [comment]
Prima di fare la macchina programmiamo il tutto.. altrimenti si paga per nulla il tempo che non si usa

**Comment by leolami** [comment]
Ok, dimmi se manca qualcosa. 
Per me la programmazione consiste in:
- isntallare la macchina, o meglio usarne una già esistente vista la breve durata del test
- farsi aprire il DB per quell'IP
- caricare un tot di progetti di Bonifica Renana sulla nuova installazione

Poi la devono usare...

**Comment by wlorenzetti** [comment]
Allora gli puoi far usare la v38 no?

**Comment by leolami** [comment]
Ok dammi l'IP

**Comment by wlorenzetti** [comment]
135.181.33.225

**Comment by leolami** [comment]
@volpe scrive questo:

**Ciao, dovresti poter raggiungere il nostro postregs con questo ip: 195.62.175.29 porta 5432**

Tu devi aprire qualcosa?

Perchè ho provato  caricare un loro progetto cambiando come specificato l'ip del DB ma non me lo carica

Se vuoi ti allegoo il progetto per mail perchè qui non me lo fa allegare

**Comment by wlorenzetti** [comment]
Allegami il progetto grazie

**Comment by wlorenzetti** [comment]
Ho verificato e non si raggiunge scrivo io a Volpe
