### ISSUE TITLE
Editing: campi non visibili a secondo dell'utente loggato

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#95]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

http://db.irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/#

In base all'utente loggato quando vado in editing non vedo i campi del primo gruppo di campi "Anagrafica sito"

### Steps to reproduce

Accedi come utente admin (sempre solita pwd)
Crea un nuovo SITO
vedrai che i campi del primo Gruppo (Anagrafica sito) sono visibili

![Image](https://github.com/user-attachments/assets/e8ea868b-20f2-45ab-9b3e-fb247b2bb6e5)

Accedi ora come utente comune_test/G3wsuite123!!
Crea un nuovo SITO
vedrai che i campi del primo Gruppo (Anagrafica sito) NON sono visibili

![Image](https://github.com/user-attachments/assets/5cafb246-90c9-46d2-9cfb-e3d4d98dc7ff)

In interrogazione invece funziona tutto correttamente, cioè vedo i campi anche con l'utente comune_test

![Image](https://github.com/user-attachments/assets/cefc23a3-253c-4c9c-9d63-88bea86ee402)

### Environment

La versione qua usata è l'ultima DEV

3.8.dev-20241016143931

### Link to your project

http://db.irpi.cnr.schede-siti.g3wsuite.it/it/map/irpi-schede-siti/qdjango/2/#

**Comment by leolami** [comment]
PS: l'utente comune_test ha un vincolo geografico: solo all'interno del Comune di Perugia

Ma non credo che questo influisca

**Comment by volterra79** [comment]
@leolami i found a Javascript error

![Screenshot from 2024-10-17 09-21-42](https://github.com/user-attachments/assets/0d33deb2-d84f-4c82-a167-3762eb7c6121)


I investigate on it
