### ISSUE TITLE
Unable to exit from photo modal

### ISSUE THREAD

**Issue by leolami** [g3w-suite/backlog#96]
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/#

Whhen I try to enlarge a photo attached to a buildings the client frezzes

### Steps to reproduce

1. Query a buildings 
2. click on aphoto attached
3. the client freeses

### Environment

3.8.dev-20241016143931

### Link to your project

https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/#

**Comment by volterra79** [comment]
@Raruto can you chek this ? Current client branch is https://github.com/g3w-suite/g3w-client/tree/context-menu on https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97](https://dev.g3wsuite.it/en/map/g3w-suite-demo/qdjango/97/
